; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .

[env:size-probe-base]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:size-probe-direct]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_SIZE_USE_DIRECT
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:size-probe-password]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_SIZE_USE_PASSWORD
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:size-probe-endcode]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_SIZE_USE_ENDCODE
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:size-probe-debug]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_SIZE_USE_DEBUG
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:size-probe-random]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_SIZE_USE_RANDOM
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:size-probe-block]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_SIZE_USE_BLOCK
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:size-probe-all]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_SIZE_USE_ALL
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/esp32dev_size_probe.cpp>

[env:m5stack-atom-console]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
monitor_eol = LF
monitor_filters = send_on_enter
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/atom_matrix_serial_console_smoke.cpp>

[env:wiznet_6300_evb_pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = wiznet_6300_evb_pico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<platformio/w6300_evb_pico2_smoke.cpp>

